name: ricknmorty
version: 1.0.0+1
publish_to: none
description: Implementation of rickandmortyapi.com API
environment: 
  sdk: '>=2.19.6 <3.0.0'
dependencies: 
  beamer: ^1.5.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  data_connection_checker_nulls: ^0.0.2
  dio: ^5.1.1
  easy_debounce: ^2.0.3
  either_dart: ^0.3.0
  equatable: ^2.0.5
  flutter_mobx: ^2.0.6+5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.4.1
  injectable: ^2.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.0
  logger: any
  mobx: ^2.2.0
  path_provider: ^2.0.14
  provider: ^6.0.5
  retrofit: ^4.0.1
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  injectable_generator: any
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.2
  mobx_codegen: ^2.2.0
  pubspec_dependency_sorter: ^1.0.3
  retrofit_generator: ^6.0.0+3
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
